# Generated by Django 4.1.7 on 2023-03-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notificationId', models.AutoField(primary_key=True, serialize=False)),
                ('notificationTimeCreated', models.DateTimeField(auto_now_add=True)),
                ('notificationMessage', models.TextField()),
                ('notificationModel', models.CharField(blank=True, max_length=50, null=True)),
                ('notificationModelId', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('notificationRecipientId', models.AutoField(primary_key=True, serialize=False)),
                ('notificationSeen', models.BooleanField(default=False)),
                ('notificationRead', models.BooleanField(default=False)),
                ('notificationTimeSeen', models.DateTimeField(null=True)),
                ('notificationTimeRead', models.DateTimeField(null=True)),
                ('notificationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='managenotifications.notification')),
                ('recipientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notificationId', 'recipientId')},
            },
        ),
    ]
