# Generated by Django 4.1.6 on 2023-02-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                ("equipmentId", models.IntegerField(primary_key=True, serialize=False)),
                ("equipmentName", models.CharField(max_length=10)),
                ("quantity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                ("stockId", models.IntegerField(primary_key=True, serialize=False)),
                ("stockDate", models.DateField(max_length=20)),
                (
                    "stockEquipmentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managestock.equipment",
                    ),
                ),
            ],
        ),
    ]
