# Generated by Django 4.1.7 on 2023-03-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managestock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stockEquipmentId',
        ),
        migrations.CreateModel(
            name='StockEquipment',
            fields=[
                ('stockEquipmentId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managestock.equipment')),
                ('stockId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managestock.stock')),
            ],
            options={
                'verbose_name': 'Stock equipment',
                'verbose_name_plural': 'Stock equipments',
                'unique_together': {('stockId', 'equipmentId')},
            },
        ),
    ]
