# Generated by Django 4.1.7 on 2023-03-18 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managestock', '0002_remove_stock_stockequipmentid_stockequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipmentName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockequipment',
            name='stockId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='managestock.stock'),
        ),
    ]
