# Generated by Django 4.1.7 on 2023-03-20 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managestock', '0004_supplier_alter_equipment_equipmentid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='supplierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managestock.supplier'),
        ),
    ]
