# Generated by Django 4.1.7 on 2023-03-21 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0002_alter_structure_structureid'),
        ('managestock', '0005_stock_supplierid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('dateCreated', models.DateTimeField(auto_created=True)),
                ('dischargeId', models.AutoField(primary_key=True, serialize=False)),
                ('structureId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discharges', to='manageusers.structure')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDischarged',
            fields=[
                ('equipmentDischargedId', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('dischargeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managestock.discharge')),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managestock.equipment')),
            ],
        ),
    ]
