# Generated by Django 4.1.7 on 2023-03-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managestock', '0006_discharge_equipmentdischarged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discharge',
            name='dateCreated',
            field=models.DateField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='equipmentdischarged',
            name='dischargeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='managestock.discharge'),
        ),
    ]
