# Generated by Django 4.1.6 on 2023-02-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("manageusers", "0001_initial"),
        ("managestock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                ("orderId", models.IntegerField(primary_key=True, serialize=False)),
                ("orderUnitPrice", models.IntegerField()),
                (
                    "orderEquipmentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managestock.equipment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "purchaseorderId",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("dateCreated", models.DateField(max_length=10)),
                (
                    "purchaseorderOrderId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managepurchaseorder.order",
                    ),
                ),
                (
                    "structureId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manageusers.structure",
                    ),
                ),
            ],
        ),
    ]
