# Generated by Django 4.1.7 on 2023-03-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managepurchaseorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='purchaseorderOrderId',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
