# Generated by Django 4.1.7 on 2023-03-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managestock', '0003_alter_equipment_equipmentname_and_more'),
        ('managepurchaseorder', '0002_remove_purchaseorder_purchaseorderorderid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderEquipment',
            fields=[
                ('purchaseOrderEquipmentId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('equipmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managestock.equipment')),
                ('purchaseOrderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='managepurchaseorder.purchaseorder')),
            ],
        ),
    ]
