# Generated by Django 4.1.7 on 2023-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managepurchaseorder', '0003_purchaseorderequipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchaseorderId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorderequipment',
            name='purchaseOrderEquipmentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
