# Generated by Django 4.1.6 on 2023-02-24 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Structure",
            fields=[
                ("structureId", models.IntegerField(primary_key=True, serialize=False)),
                ("structureName", models.CharField(max_length=8)),
                ("structureAdress", models.IntegerField()),
                ("structureNature", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("userId", models.IntegerField(primary_key=True, serialize=False)),
                ("userName", models.CharField(max_length=200)),
                ("userEmail", models.CharField(max_length=100)),
                ("userPassword", models.FloatField(max_length=100)),
                (
                    "userStructureId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="manageusers.structure",
                    ),
                ),
            ],
        ),
    ]
