# Generated by Django 4.1.7 on 2023-03-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0002_alter_structure_structureid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='structure',
            old_name='structureAdress',
            new_name='structureAddress',
        ),
    ]
