# Generated by Django 4.1.7 on 2023-03-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0003_rename_structureadress_structure_structureaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeFirstName', models.CharField(max_length=50)),
                ('employeeLastName', models.CharField(max_length=50)),
                ('structureId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='manageusers.structure')),
            ],
        ),
        migrations.AddField(
            model_name='structure',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manageusers.employee'),
        ),
    ]
