# Generated by Django 4.1.7 on 2023-04-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0007_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='structure_head',
            field=models.BooleanField(default=False, verbose_name='Chef de structure?'),
        ),
    ]
