# Generated by Django 4.1.7 on 2023-04-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageusers', '0009_set_employee_structure_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='structure_subhead',
            field=models.BooleanField(default=False, verbose_name='Sous-chef de structure?'),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='manageusers.employee'),
        ),
        migrations.CreateModel(
            name='StructureSubHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageusers.employee')),
                ('structureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheads', to='manageusers.structure')),
            ],
            options={
                'unique_together': {('structureId', 'employeeId')},
            },
        ),
    ]
